export const TOGGLE_GAME_ACTIVE = 'TOGGLE_GAME_ACTIVE';
export const CHANGE_CARDS_SKIRT = 'CHANGE_CARDS_SKIRT';
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const SET_TOTAL_TIME = 'SET_TOTAL_TIME';
export const RESET_GAME = 'RESET_GAME';
export const FLIP_CARD_UP = 'FLIP_CARD_UP';
export const FLIP_FIRST_CARD_UP = 'FLIP_FIRST_CARD_UP';
export const SELECT_CORRECT_CARD = 'SELECT_CORRECT_CARD';
export const FLIP_CARDS_DOWN = 'FLIP_CARDS_DOWN';
export const HIDE_CARDS = 'HIDE_CARDS';
export const RESET_CARDS = 'RESET_CARDS';
export const FILL_PROFILE = 'FILL_PROFILE';
export const SEND_RESULT = 'SEND_RESULT';

